#!/usr/bin/env node
// Generates generated/ts/schema.ts (the `paths` and `components` types) from openapi.yaml
// with openapi-typescript. The fetch wrapper in src/client.ts is typed against it.
import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import openapiTS, { astToString } from 'openapi-typescript';
import { generatedDir, openapiPath } from './lib.mjs';

const outDir = path.join(generatedDir, 'ts');
const outFile = path.join(outDir, 'schema.ts');
mkdirSync(outDir, { recursive: true });

const header = `// GENERATED by packages/contracts/scripts/generate-ts.mjs from openapi.yaml. Do not edit.\n/* eslint-disable */\n`;

if (!existsSync(openapiPath)) {
  writeFileSync(
    outFile,
    `${header}// openapi.yaml was absent at generation time; the client is untyped until it exists.\n` +
      `export type paths = Record<string, never>;\nexport type components = Record<string, never>;\n` +
      `export type operations = Record<string, never>;\n`,
  );
  console.warn(
    `contracts:generate:ts  openapi.yaml absent — wrote an empty ${path.relative(process.cwd(), outFile)}`,
  );
  process.exit(0);
}

const ast = await openapiTS(new URL(`file://${openapiPath}`), {
  alphabetize: true,
  exportType: true,
  enum: false,
});
writeFileSync(outFile, header + astToString(ast));
console.log(`contracts:generate:ts  wrote ${path.relative(process.cwd(), outFile)}`);
