#!/usr/bin/env node
// Writes the two Swift files the iOS app takes from the rest of the repository, so neither is
// typed by hand:
//
//   CoreHub/Generated/Tokens.swift  ← packages/ui-tokens/tokens.json (colours in both themes,
//                                     spacing, radii, type sizes, layout, motion, glass)
//   CoreHub/Generated/Product.swift ← packages/contracts/src/product.ts (the product's name,
//                                     its id and the pairing QR type, current and legacy)
//   CoreHub/Resources/<lang>.lproj/InfoPlist.strings ← the product's name and the
//                                     `permissions.*` sentences of CoreHub/i18n/<lang>.json,
//                                     so the system's own prompts speak Arabic and English
//
//   node apps/ios/scripts/generate-swift.mjs          # write them
//   node apps/ios/scripts/generate-swift.mjs --check  # fail when a committed file is stale (CI)
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const iosRoot = path.resolve(here, '..');
const repoRoot = path.resolve(iosRoot, '..', '..');
const appDir = path.join(iosRoot, 'CoreHub');
const check = process.argv.includes('--check');

const HEADER = (source) =>
  `// Generated by apps/ios/scripts/generate-swift.mjs from ${source}. Do not edit;\n` +
  `// change the source and run \`node apps/ios/scripts/generate-swift.mjs\`.\n`;

/** `bg-raised` → `bgRaised`; a leading digit gets an `s` (`space.1` → `s1`). */
export function swiftName(key) {
  const camel = key.replace(/[-_.]([a-z0-9])/g, (_, c) => c.toUpperCase());
  return /^[0-9]/.test(camel) ? `s${camel}` : camel;
}

/** `#rrggbb` or `#rrggbbaa` → `RGBA(r, g, b, a)` literal with components in 0…1. */
export function rgba(hex) {
  const m = /^#([0-9a-f]{6})([0-9a-f]{2})?$/i.exec(hex);
  if (!m) throw new Error(`generate-swift: not a colour: ${hex}`);
  const n = parseInt(m[1], 16);
  const a = m[2] ? parseInt(m[2], 16) / 255 : 1;
  const c = (v) => (v / 255).toFixed(4);
  return `RGBA(${c((n >> 16) & 255)}, ${c((n >> 8) & 255)}, ${c(n & 255)}, ${a.toFixed(4)})`;
}

/** `1.25rem` → 20, `12px` → 12, `70%` → 0.7, `120ms` → 0.12 (seconds). */
export function points(value) {
  const text = String(value).trim();
  let m;
  if ((m = /^(-?[\d.]+)rem$/.exec(text))) return Number(m[1]) * 16;
  if ((m = /^(-?[\d.]+)px$/.exec(text))) return Number(m[1]);
  if ((m = /^(-?[\d.]+)%$/.exec(text))) return Number(m[1]) / 100;
  if ((m = /^(-?[\d.]+)ms$/.exec(text))) return Number(m[1]) / 1000;
  if (/^-?[\d.]+$/.test(text)) return Number(text);
  return null;
}

const num = (n) => (Number.isInteger(n) ? `${n}` : `${Number(n.toFixed(4))}`);

function numericEnum(name, doc, group) {
  const lines = [];
  for (const [key, value] of Object.entries(group)) {
    if (key.startsWith('$')) continue;
    const n = points(value);
    if (n === null) continue;
    lines.push(`    static let ${swiftName(key)}: CGFloat = ${num(n)}`);
  }
  return `/// ${doc}\nenum ${name} {\n${lines.join('\n')}\n}\n`;
}

export function tokensSwift(tokens) {
  const light = tokens.themes.light;
  const dark = tokens.themes.dark;
  const keys = Object.keys(light).filter((k) => !k.startsWith('$'));
  for (const key of keys)
    if (!(key in dark)) throw new Error(`generate-swift: ${key} missing from the dark theme`);
  const fields = keys.map((k) => `    let ${swiftName(k)}: RGBA`).join('\n');
  const palette = (theme) =>
    keys.map((k) => `        ${swiftName(k)}: ${rgba(theme[k])}`).join(',\n');
  const glass = Object.entries(tokens.glass.levels)
    .map(
      ([level, g]) =>
        `        GlassLevel(level: ${level}, blur: ${num(points(g.blur))}, alpha: ${num(g.alpha)}, borderAlpha: ${num(g.borderAlpha)}, saturate: ${num(g.saturate)})`,
    )
    .join(',\n');
  const motion = Object.entries(tokens.motion)
    .filter(([k, v]) => !k.startsWith('$') && /ms$/.test(String(v)))
    .map(([k, v]) => `    static let ${swiftName(k)}: Double = ${num(points(v))}`)
    .join('\n');
  const fontSizes = Object.fromEntries(
    Object.entries(tokens.font).filter(([k]) => k.startsWith('size-') || k.startsWith('leading-')),
  );
  const control = Object.fromEntries(
    Object.entries(tokens.control).filter(([k]) => !k.startsWith('$') && !k.startsWith('font-')),
  );
  return `${HEADER('packages/ui-tokens/tokens.json')}
import CoreGraphics

/// One colour of a theme, components in 0…1.
struct RGBA: Equatable {
    let red: Double
    let green: Double
    let blue: Double
    let alpha: Double

    init(_ red: Double, _ green: Double, _ blue: Double, _ alpha: Double) {
        self.red = red
        self.green = green
        self.blue = blue
        self.alpha = alpha
    }
}

/// Every colour role of a theme (tokens.json \`themes\`), named by role, never by hue.
struct Palette: Equatable {
${fields}
}

extension Palette {
    static let light = Palette(
${palette(light)}
    )

    static let dark = Palette(
${palette(dark)}
    )

    /// The token keys in tokens.json order, for the tests.
    static let tokenKeys: [String] = [${keys.map((k) => `"${k}"`).join(', ')}]
}

/// One level of the glass scale (0 solid … 3 full); only floating chrome uses it.
struct GlassLevel: Equatable {
    let level: Int
    let blur: CGFloat
    let alpha: Double
    let borderAlpha: Double
    let saturate: Double
}

enum Glass {
    static let defaultLevel = ${tokens.glass.default}
    static let levels: [GlassLevel] = [
${glass}
    ]
}

${numericEnum('Space', 'Spacing in points (1rem = 16pt).', tokens.space)}
${numericEnum('Radius', 'Corner radii in points.', tokens.radius)}
${numericEnum('FontSize', 'Type sizes in points; `leading*` are line-height multipliers.', fontSizes)}
${numericEnum('Layout', 'Layout sizes in points; `bubbleMax` is a fraction of the column.', tokens.layout)}
${numericEnum('Control', 'The segmented control and the control heights, in points.', control)}
/// Durations in seconds.
enum Motion {
${motion}
}
`;
}

export function productSwift(product) {
  const { PRODUCT, derived, LEGACY } = product;
  return `${HEADER('packages/contracts/src/product.ts')}
/// What the product is called and the conventions named after it (ADR 0017).
enum Product {
    static let id = "${PRODUCT.id}"
    static let name = "${PRODUCT.name}"
    static let nameAr = "${PRODUCT.nameAr}"
    static let repository = "${PRODUCT.repository}"
    /// The QR payload's \`type\` the hub writes today.
    static let pairingType = "${derived.pairingType}"
    /// The \`type\` an older hub wrote; still read.
    static let legacyPairingType = "${LEGACY.pairingType}"
    /// Keychain service and defaults prefix.
    static let storagePrefix = "${derived.storagePrefix}"
}
`;
}

/** `"a\"b"` — a .strings literal. */
const stringsLiteral = (text) => `"${String(text).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;

export function infoPlistStrings(language, product, catalogue) {
  const name = language === 'ar' ? product.PRODUCT.nameAr : product.PRODUCT.name;
  const entries = {
    CFBundleDisplayName: name,
    CFBundleName: name,
    NSCameraUsageDescription: catalogue.permissions.camera,
    NSLocalNetworkUsageDescription: catalogue.permissions.local_network,
    NSMicrophoneUsageDescription: catalogue.permissions.microphone,
    NSSpeechRecognitionUsageDescription: catalogue.permissions.speech,
  };
  const lines = Object.entries(entries).map(([k, v]) => `${k} = ${stringsLiteral(v)};`);
  return `/* Generated by apps/ios/scripts/generate-swift.mjs. Do not edit. */\n${lines.join('\n')}\n`;
}

async function main() {
  const tokens = JSON.parse(
    readFileSync(path.join(repoRoot, 'packages/ui-tokens/tokens.json'), 'utf8'),
  );
  const product = await import(path.join(repoRoot, 'packages/contracts/src/product.ts'));
  const files = {
    'Generated/Tokens.swift': tokensSwift(tokens),
    'Generated/Product.swift': productSwift(product),
  };
  for (const language of ['ar', 'en']) {
    const catalogue = JSON.parse(
      readFileSync(path.join(appDir, 'i18n', `${language}.json`), 'utf8'),
    );
    files[`Resources/${language}.lproj/InfoPlist.strings`] = infoPlistStrings(
      language,
      product,
      catalogue,
    );
  }
  let stale = 0;
  for (const [name, content] of Object.entries(files)) {
    const file = path.join(appDir, name);
    if (check) {
      const current = existsSync(file) ? readFileSync(file, 'utf8') : '';
      if (current !== content) {
        stale += 1;
        console.error(
          `generate-swift  ${path.relative(repoRoot, file)} is stale; run node apps/ios/scripts/generate-swift.mjs`,
        );
      }
    } else {
      mkdirSync(path.dirname(file), { recursive: true });
      writeFileSync(file, content);
      console.log(`generate-swift  wrote ${path.relative(repoRoot, file)}`);
    }
  }
  if (stale > 0) process.exit(1);
  if (check) console.log('generate-swift  OK — every generated file matches its source');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]))
  await main();
