// Generated by scripts/icons/agent-marks-mobile.mjs from packages/web/src/ui/brand/marks.tsx; do not edit by hand.
package hub.core.android.ui.components

import hub.core.android.R

/** The agents' own marks the app carries, by catalog slug (the web's `agentMark`). */
object AgentMarks {
    val drawables: Map<String, Int> = mapOf(
        "hermes" to R.drawable.agent_mark_hermes,
        "claude-code" to R.drawable.agent_mark_claude_code,
        "codex" to R.drawable.agent_mark_codex,
        "gemini-cli" to R.drawable.agent_mark_gemini_cli,
        "opencode" to R.drawable.agent_mark_opencode,
        "qwen-code" to R.drawable.agent_mark_qwen_code,
        "kimi-code" to R.drawable.agent_mark_kimi_code,
        "pi" to R.drawable.agent_mark_pi,
        "direct" to R.drawable.agent_mark_direct,
    )

    /** The mark of the agent with this catalog slug; null for one we do not ship. */
    fun of(slug: String?): Int? = slug?.let { drawables[it] }
}
