#!/usr/bin/env node
// Lucide icons (https://lucide.dev, ISC; THIRD-PARTY-NOTICES.md) for the web client and the
// desktop app, which shows the web client.
//
//   node scripts/icons/lucide-web.mjs          # rewrite packages/web/src/ui/lucide.generated.ts
//   node scripts/icons/lucide-web.mjs --check  # exit 1 when the committed file differs
//
// The names are the ones `packages/web/src/ui/icons.tsx` asks for with `lucide('<name>')` or
// `shapes('<name>')`, so the client carries only the outlines it draws and there is no second
// list to keep in step.
// The outlines come from the pinned `lucide-static` package (its icon-nodes.json) — the same
// source `lucide-mobile.mjs` writes the iOS and Android icons from, so one name draws one shape
// on every platform (docs/design/family.md).
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import * as prettier from 'prettier';

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const require = createRequire(import.meta.url);
const check = process.argv.includes('--check');

const pkgDir = path.dirname(require.resolve('lucide-static/package.json'));
const version = JSON.parse(readFileSync(path.join(pkgDir, 'package.json'), 'utf8')).version;
const nodes = JSON.parse(readFileSync(path.join(pkgDir, 'icon-nodes.json'), 'utf8'));

const iconsFile = path.join(repo, 'packages/web/src/ui/icons.tsx');
const outFile = path.join(repo, 'packages/web/src/ui/lucide.generated.ts');

const names = [
  ...new Set(
    [...readFileSync(iconsFile, 'utf8').matchAll(/(?:lucide|shapes)\('([a-z0-9-]+)'\)/g)].map(
      (m) => m[1],
    ),
  ),
].sort();
if (names.length === 0) throw new Error('icons.tsx asks for no lucide(...) icon');
for (const name of names) {
  if (!nodes[name]) throw new Error(`lucide-static ${version} has no icon named "${name}"`);
}

const q = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const attrs = (a) =>
  `{ ${Object.entries(a)
    .map(([k, v]) => `${/^[a-z]+$/i.test(k) ? k : q(k)}: ${q(v)}`)
    .join(', ')} }`;

const body = names
  .map((name) => {
    const els = nodes[name].map(([tag, a]) => `    [${q(tag)}, ${attrs(a)}],`).join('\n');
    return `  ${q(name)}: [\n${els}\n  ],`;
  })
  .join('\n');

const raw = `// Generated by scripts/icons/lucide-web.mjs from lucide-static ${version} (ISC licence,
// Copyright (c) Lucide Icons and Contributors; THIRD-PARTY-NOTICES.md). Do not edit by hand:
// ask for a new icon with lucide('<name>') in icons.tsx and run \`pnpm icons:lucide\`.
/*! @license lucide-static ${version} — ISC License, Copyright (c) Lucide Icons and Contributors.
 * Permission to use, copy, modify, and/or distribute this software for any purpose with or without
 * fee is hereby granted, provided that the above copyright notice and this permission notice appear
 * in all copies. THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
 * REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO
 * EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY
 * DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
 * NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
 * OF THIS SOFTWARE. Some icons derive from Feather (MIT, Copyright (c) 2013-present Cole Bemis). */
export type LucideNode = readonly [tag: string, attrs: Readonly<Record<string, string>>];

export const lucideVersion = ${q(version)};

export const lucideNodes = {
${body}
} as const satisfies Record<string, readonly LucideNode[]>;

export type LucideName = keyof typeof lucideNodes;
`;
// Formatted like the rest of the repository, so `prettier --check` agrees with this script.
const out = await prettier.format(raw, {
  ...(await prettier.resolveConfig(outFile)),
  filepath: outFile,
});

if (check) {
  let current = '';
  try {
    current = readFileSync(outFile, 'utf8');
  } catch {
    // missing counts as different
  }
  if (current !== out) {
    console.error(`${path.relative(repo, outFile)} is out of date: run pnpm icons:lucide`);
    process.exit(1);
  }
  console.log(`lucide web icons up to date (${names.length} icons, lucide-static ${version})`);
} else {
  writeFileSync(outFile, out);
  console.log(
    `wrote ${path.relative(repo, outFile)} (${names.length} icons, lucide-static ${version})`,
  );
}
