#!/usr/bin/env node
// The companies' logos beside each provider in "Add a provider" (DECISIONS §146): a small mark,
// one colour, tinted by the page, only so people recognise the company.
//
//   node scripts/icons/vendor-logos.mjs          # rewrite packages/web/src/ui/brand/vendor-logos.generated.ts
//   node scripts/icons/vendor-logos.mjs --check  # exit 1 when the committed file differs
//
// Sources, pinned (THIRD-PARTY-NOTICES.md): `@lobehub/icons-static-svg` 1.95.1 (MIT) — the same
// package the agents' marks come from — and, for Deepgram, which it lacks, `simple-icons`
// 16.33.0 (CC0-1.0). The SVGs are fetched once from jsDelivr into ~/.cache/corehub/vendor-logos
// and only their path data is kept. A company with neither (LiteLLM, Nous Portal, a custom
// endpoint) gets a monogram in the client, drawn from its name.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as prettier from 'prettier';

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const check = process.argv.includes('--check');
const outFile = path.join(repo, 'packages/web/src/ui/brand/vendor-logos.generated.ts');
const cache = path.join(homedir(), '.cache', 'corehub', 'vendor-logos');

const LOBE = { pkg: '@lobehub/icons-static-svg', version: '1.95.1' };
const SIMPLE = { pkg: 'simple-icons', version: '16.33.0' };

/** Logo name → where its SVG comes from. */
const LOGOS = {
  anthropic: [LOBE, 'anthropic'],
  claude: [LOBE, 'claude'],
  openai: [LOBE, 'openai'],
  openrouter: [LOBE, 'openrouter'],
  gemini: [LOBE, 'gemini'],
  groq: [LOBE, 'groq'],
  mistral: [LOBE, 'mistral'],
  deepseek: [LOBE, 'deepseek'],
  xai: [LOBE, 'xai'],
  grok: [LOBE, 'grok'],
  ollama: [LOBE, 'ollama'],
  lmstudio: [LOBE, 'lmstudio'],
  elevenlabs: [LOBE, 'elevenlabs'],
  azure: [LOBE, 'azure'],
  minimax: [LOBE, 'minimax'],
  kimi: [LOBE, 'kimi'],
  meta: [LOBE, 'meta'],
  antigravity: [LOBE, 'antigravity'],
  devin: [LOBE, 'devin'],
  deepgram: [SIMPLE, 'deepgram'],
};

async function svgOf([source, name]) {
  const dir = path.join(cache, `${source.pkg.replace('/', '__')}@${source.version}`);
  const file = path.join(dir, `${name}.svg`);
  if (!existsSync(file)) {
    const url = `https://cdn.jsdelivr.net/npm/${source.pkg}@${source.version}/icons/${name}.svg`;
    const response = await fetch(url);
    if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
    mkdirSync(dir, { recursive: true });
    writeFileSync(file, await response.text());
  }
  return readFileSync(file, 'utf8');
}

function pathsOf(svg, name) {
  if (!/viewBox="0 0 24 24"/.test(svg)) throw new Error(`${name}: not a 24×24 icon`);
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (paths.length === 0) throw new Error(`${name}: no path`);
  return paths;
}

const entries = [];
for (const [name, source] of Object.entries(LOGOS)) {
  entries.push([name, pathsOf(await svgOf(source), name)]);
}

const body = `// Generated by scripts/icons/vendor-logos.mjs — do not edit by hand.
// Path data from ${LOBE.pkg} ${LOBE.version} (MIT) and, for Deepgram, ${SIMPLE.pkg} ${SIMPLE.version}
// (CC0-1.0); see THIRD-PARTY-NOTICES.md. The marks belong to their owners and are shown only to
// name the company a provider is.

/** Each company's logo as the path data of a 24×24 icon, drawn in \`currentColor\`. */
export const VENDOR_LOGO_PATHS: Readonly<Record<string, readonly string[]>> = {
${entries.map(([name, paths]) => `  ${JSON.stringify(name)}: ${JSON.stringify(paths)},`).join('\n')}
};
`;
const options = (await prettier.resolveConfig(outFile)) ?? {};
const formatted = await prettier.format(body, { ...options, filepath: outFile });
if (check) {
  const current = existsSync(outFile) ? readFileSync(outFile, 'utf8') : '';
  if (current !== formatted) {
    console.error('vendor-logos: packages/web/src/ui/brand/vendor-logos.generated.ts is stale');
    process.exit(1);
  }
  console.log('vendor-logos: OK');
} else {
  writeFileSync(outFile, formatted);
  console.log(`vendor-logos: wrote ${entries.length} logos`);
}
