// The Kotlin client generated from packages/contracts/openapi.yaml (ADR 0003). Nothing in this
// module is written by hand: its sources are the generator's output, git-ignored and made by
// `pnpm contracts:generate:native` (CI runs it before Gradle). A client never hand-types an
// API path; `pnpm contracts:check-clients` scans apps/android for one.
plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization)
}

val generated = rootProject.file("../../packages/contracts/generated/kotlin/src/main/kotlin")

kotlin {
    jvmToolchain(17)
    sourceSets["main"].kotlin.srcDir(generated)
}

val checkGenerated by tasks.registering {
    doFirst {
        if (!generated.resolve("hub/core/client/infrastructure/ApiClient.kt").exists())
            throw GradleException(
                "The generated Kotlin client is missing ($generated). " +
                    "Run `pnpm contracts:generate:native` from the repository root (needs Java 17+).",
            )
    }
}
tasks.named("compileKotlin") { dependsOn(checkGenerated) }

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    compilerOptions.suppressWarnings.set(true)
}

dependencies {
    api(libs.kotlinx.coroutines.core)
    api(libs.kotlinx.serialization.json)
    api(libs.okhttp)
}
