// Database composition: Drizzle over SQLite (default, file under DATA_DIR) or PostgreSQL
// (DATABASE_URL). Module tables live in src/modules/<name>/schema.ts and are re-exported by
// src/db/schema.ts (the single typed schema); migrations generated by drizzle-kit land in
// ./drizzle and are applied here on boot.
import { existsSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import Database from 'better-sqlite3';
import { drizzle as drizzleSqlite, type BetterSQLite3Database } from 'drizzle-orm/better-sqlite3';
import { migrate as migrateSqlite } from 'drizzle-orm/better-sqlite3/migrator';
import { drizzle as drizzlePg, type NodePgDatabase } from 'drizzle-orm/node-postgres';
import { migrate as migratePg } from 'drizzle-orm/node-postgres/migrator';
import { sql } from 'drizzle-orm';
import pg from 'pg';
import * as schema from '../db/schema.js';
import type { Logger } from '../lib/logger.js';
import type { DatabaseConfig } from './config.js';

export const packageRoot = fileURLToPath(new URL('../../', import.meta.url));
export const migrationsFolder = path.join(packageRoot, 'drizzle');

export type HubSchema = typeof schema;
export type SqliteDatabase = BetterSQLite3Database<HubSchema>;
// The schema is authored in sqlite-core; the PostgreSQL variant is produced mechanically later
// (src/db/README.md), so the pg instance is untyped until then.
export type PostgresDatabase = NodePgDatabase;

export type HubDatabase =
  | {
      kind: 'sqlite';
      db: SqliteDatabase;
      migrate(): Promise<void>;
      ping(): Promise<void>;
      close(): Promise<void>;
    }
  | {
      kind: 'postgres';
      db: PostgresDatabase;
      migrate(): Promise<void>;
      ping(): Promise<void>;
      close(): Promise<void>;
    };

export function hasMigrations(folder: string = migrationsFolder): boolean {
  return existsSync(path.join(folder, 'meta', '_journal.json'));
}

export function createDatabase(config: DatabaseConfig, log: Logger): HubDatabase {
  if (config.kind === 'postgres') {
    const pool = new pg.Pool({ connectionString: config.url });
    const db = drizzlePg(pool);
    return {
      kind: 'postgres',
      db,
      async migrate() {
        if (!hasMigrations()) return log.info('db: no migrations to apply yet');
        await migratePg(db, { migrationsFolder });
        log.info('db: migrations applied (postgres)');
      },
      async ping() {
        await db.execute(sql`select 1`);
      },
      async close() {
        await pool.end();
      },
    };
  }

  mkdirSync(path.dirname(config.file), { recursive: true });
  const sqlite = new Database(config.file);
  sqlite.pragma('journal_mode = WAL');
  sqlite.pragma('foreign_keys = ON');
  const db = drizzleSqlite(sqlite, { schema });
  return {
    kind: 'sqlite',
    db,
    async migrate() {
      if (!hasMigrations()) return log.info('db: no migrations to apply yet');
      migrateSqlite(db, { migrationsFolder });
      log.info('db: migrations applied (sqlite)');
    },
    async ping() {
      db.run(sql`select 1`);
    },
    async close() {
      sqlite.close();
    },
  };
}
