// The app's icons are Lucide (docs/design/family.md, "Icons"): the same outlines the web and the
// Android app draw, generated by scripts/icons/lucide-mobile.mjs. SF Symbols are not used for
// anything the other clients also show, so one idea has one picture on every platform.
import SwiftUI

/// A Lucide icon at a size in points that grows with Dynamic Type, like the text beside it.
struct LucideIcon: View {
    let icon: Lucide
    var size: CGFloat
    @ScaledMetric(relativeTo: .body) private var scale: CGFloat = 1

    init(_ icon: Lucide, size: CGFloat = 18) {
        self.icon = icon
        self.size = size
    }

    var body: some View {
        Image(lucide: icon)
            .resizable()
            .scaledToFit()
            .frame(width: size * scale, height: size * scale)
            .accessibilityHidden(true)
    }
}

/// A title with its Lucide icon, for list rows and buttons (a menu takes `Image(lucide:)`).
struct LucideLabel: View {
    let title: String
    let icon: Lucide
    var size: CGFloat = 18

    init(_ title: String, icon: Lucide, size: CGFloat = 18) {
        self.title = title
        self.icon = icon
        self.size = size
    }

    var body: some View {
        Label {
            Text(title)
        } icon: {
            LucideIcon(icon, size: size)
        }
    }
}

extension View {
    /// At least the 44-point square Apple asks of anything a finger presses, without growing
    /// what is drawn (docs/design/family.md, "Tap targets").
    func tapTarget(_ side: CGFloat = 44) -> some View {
        frame(minWidth: side, minHeight: side).contentShape(Rectangle())
    }

    /// A press area wider than what is drawn, for a control that must stay small inside a
    /// dense row (the composer's round buttons): the layout does not move.
    func hitSlop(_ points: CGFloat = 5) -> some View {
        contentShape(Rectangle().inset(by: -points))
    }
}
