#!/usr/bin/env node
// Generates dist/tokens.css (CSS custom properties), dist/tokens.js and dist/tokens.d.ts from
// tokens.json. The CSS is the only styling input of packages/web; the JSON stays the source
// every other exporter (Kotlin/Swift) reads.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(path.join(root, 'tokens.json'), 'utf8'));
const p = tokens.prefix;
const dist = path.join(root, 'dist');
mkdirSync(dist, { recursive: true });

const hexToRgb = (hex) => {
  const h = hex.replace('#', '');
  const n = parseInt(h.slice(0, 6), 16);
  return `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`;
};

function themeBlock(theme) {
  const lines = [];
  for (const [name, value] of Object.entries(theme)) {
    if (name === 'glassTint') lines.push(`  --${p}-glass-tint: ${hexToRgb(value)};`);
    else lines.push(`  --${p}-color-${name}: ${value};`);
  }
  return lines.join('\n');
}

function glassBlock(level) {
  const g = tokens.glass.levels[level];
  return [
    `  --${p}-glass-level: ${level};`,
    `  --${p}-glass-blur: ${g.blur};`,
    `  --${p}-glass-alpha: ${g.alpha};`,
    `  --${p}-glass-border-alpha: ${g.borderAlpha};`,
    `  --${p}-glass-saturate: ${g.saturate};`,
    `  --${p}-glass-shadow: ${g.shadow};`,
  ].join('\n');
}

const scalar = (group, prefix) =>
  Object.entries(tokens[group])
    .filter(([k]) => !k.startsWith('$'))
    .map(([k, v]) => `  --${p}-${prefix}-${k}: ${v};`)
    .join('\n');

const css = `/* GENERATED by packages/ui-tokens/scripts/build.mjs from tokens.json. Do not edit. */
:root {
  color-scheme: light;
${themeBlock(tokens.themes.light)}
${glassBlock(String(tokens.glass.default))}
${scalar('space', 'space')}
${scalar('radius', 'radius')}
${scalar('font', 'font')}
${scalar('layout', 'layout')}
${scalar('motion', 'motion')}
${scalar('z', 'z')}
  /* Derived: the glass surface itself. Chrome uses these three; content never does. */
  --${p}-glass-bg: rgb(var(--${p}-glass-tint) / var(--${p}-glass-alpha));
  --${p}-glass-border: color-mix(in srgb, var(--${p}-color-border) calc(var(--${p}-glass-border-alpha) * 100%), transparent);
  --${p}-glass-filter: blur(var(--${p}-glass-blur)) saturate(var(--${p}-glass-saturate));
}
:root[data-theme='dark'] {
  color-scheme: dark;
${themeBlock(tokens.themes.dark)}
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
    color-scheme: dark;
${themeBlock(tokens.themes.dark)}
  }
}
${Object.keys(tokens.glass.levels)
  .map((level) => `:root[data-glass='${level}'] {\n${glassBlock(level)}\n}`)
  .join('\n')}
/* The person asked the OS for less transparency: every level collapses to solid. */
@media (prefers-reduced-transparency: reduce) {
  :root,
  :root[data-glass] {
${glassBlock('0')}
  }
}
/* The person asked the OS for less motion: transitions become instant. */
@media (prefers-reduced-motion: reduce) {
  :root {
    --${p}-motion-fast: 0ms;
    --${p}-motion-normal: 0ms;
    --${p}-motion-slow: 0ms;
  }
}
`;
writeFileSync(path.join(dist, 'tokens.css'), css);

const js = `// GENERATED by packages/ui-tokens/scripts/build.mjs from tokens.json. Do not edit.
export const tokens = ${JSON.stringify(tokens, null, 2)};
export const THEMES = ['light', 'dark'];
export const GLASS_LEVELS = ['0', '1', '2', '3'];
export const DEFAULT_GLASS = '${tokens.glass.default}';
export const PREFIX = '${p}';
export function cssVar(name) { return \`var(--${p}-\${name})\`; }
`;
writeFileSync(path.join(dist, 'tokens.js'), js);

const dts = `// GENERATED by packages/ui-tokens/scripts/build.mjs from tokens.json. Do not edit.
export type ThemeName = 'light' | 'dark';
export type GlassLevel = '0' | '1' | '2' | '3';
export type ColorName = ${Object.keys(tokens.themes.light)
  .filter((k) => k !== 'glassTint')
  .map((k) => `'${k}'`)
  .join(' | ')};
export interface GlassSpec { blur: string; alpha: number; borderAlpha: number; saturate: number; shadow: string }
export interface Tokens {
  version: number;
  prefix: string;
  themes: Record<ThemeName, Record<ColorName | 'glassTint', string>>;
  glass: { default: number; levels: Record<GlassLevel, GlassSpec> };
  space: Record<string, string>;
  radius: Record<string, string>;
  font: Record<string, string>;
  layout: Record<string, string>;
  motion: Record<string, string>;
  z: Record<string, number>;
  contrast: { pairs: Array<{ fg: ColorName; bg: ColorName | 'glass'; min: number }> };
}
export declare const tokens: Tokens;
export declare const THEMES: readonly ThemeName[];
export declare const GLASS_LEVELS: readonly GlassLevel[];
export declare const DEFAULT_GLASS: GlassLevel;
export declare const PREFIX: string;
export declare function cssVar(name: string): string;
`;
writeFileSync(path.join(dist, 'tokens.d.ts'), dts);
console.log(`ui-tokens  wrote dist/tokens.css, dist/tokens.js, dist/tokens.d.ts`);
